apiVersion: v1
kind: ConfigMap
metadata:
  name: sputnik-metrics-prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval:     3s
      evaluation_interval: 3s
    scrape_configs:
      - job_name: 'statsd'
        static_configs:
          - targets: ['sputnik-metrics-statsd-scrape:9102']
      - job_name: 'prometheus'
        static_configs:
          - targets: ['sputnik-metrics-prometheus:9090']
      - job_name: 'otel'
        static_configs:
          - targets: ['opentelemetry-collector:8889']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sputnik-metrics-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sputnik-metrics-prometheus
  template:
    metadata:
      labels:
        app: sputnik-metrics-prometheus
    spec:
      containers:
      - name: sputnik-metrics-prometheus
        image: prom/prometheus
        ports:
        - name: tcp
          containerPort: 9090
        args:
          - --config.file=/tmp/prometheus.yaml
        volumeMounts:
          - mountPath: /tmp
            name: sputnik-metrics-config-files
      volumes:
        - name: sputnik-metrics-config-files
          configMap:
            name: sputnik-metrics-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: sputnik-metrics-prometheus
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: sputnik-metrics-prometheus